language: c
script: make
compiler:
    - clang
    - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libusb-1.0-0-dev


# Coverity autoscan
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   secure: "q0IS/BuGHeuMtKnoy6gMt9Epn3JeZ9wuHdIqwplyTqklENP2DPS2s5axcEf9cXJxE0hQKsvXtD87QEH0+ct3AsjqfiNWvs++CaLTNF8DVfpEe96h3+sJuaVZQL5RxF7qR/rhSRCk67AXqn+nu9b9wBtk5+7REFVs2Pn6gxoTAMs="

addons:
  coverity_scan:
    project:
      name: "daniel-dressler/ippusbd"
      description: "IPP over USB daemon driver for linux"
    notification_email: danieru.dressler@gmail.com
    build_command_prepend:
    build_command: make
    branch_pattern: coverity_check

