language: c
script: make
compiler:
    - clang
    - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libusb-1.0-0-dev


# Coverity autoscan
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
     secure: "Hfs5xWhBp/ZTeFRIUoDwy/q2Jv6dDHlaeNkAdExg4vUjJcvZQuU0XUSaj99JFc7fIpzAVKYn4RFm1HSpqFXBVtSCfuHhtLzw2LpzznLRFKeq2EPKkhJVMCVGCiW5rG8XbrXhfX/SPVNmEMySa3gNpwRRxZ+hgcolBFl3+2FSfjM="

addons:
  coverity_scan:
    project:
      name: "daniel-dressler/ippusbd"
      description: "IPP over USB daemon driver for linux"
    notification_email: danieru.dressler@gmail.com
    build_command_prepend:
    build_command: make
    branch_pattern: master

