language: c
script: make
compiler:
    - clang
    - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libusb-1.0-0-dev


# Coverity autoscan
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
    secure: "CtAND8k/8Lfs6o4dmrD9Jp4yLjLQRrv5TZA1MkhSO/LRfViKlbzy7ENv1/ku0xgtnsegFRDFY75/dLHxZUiax5TGNVrHqpkkGSE9h2a5YYHxbOtINb8Hdzk+S2/EN9YPmrOEX1ZjMg/wH08c3MntdW6gDUuddQhjCuaNnH+8fUc="


addons:
  coverity_scan:
    project:
      name: "daniel-dressler/ippusbxd"
      description: "IPP over USB daemon driver for linux"
    notification_email: danieru.dressler@gmail.com
    build_command_prepend:
    build_command: make
    branch_pattern: master

